In [2]:
import numpy as np

# Q1
arr = np.array([1, 2, 3, 4, 5])

arr_add = arr + 2

arr_mul = arr * 3

arr_div = arr / 2

print("Original Array:", arr)
print("After Addition:", arr_add)
print("After Multiplication:", arr_mul)
print("After Division:", arr_div)

Original Array: [1 2 3 4 5]
After Addition: [3 4 5 6 7]
After Multiplication: [ 3  6  9 12 15]
After Division: [0.5 1.  1.5 2.  2.5]


In [3]:

import numpy as np

# Q2 a)
arr_rev = np.array([1, 2, 3, 6, 4, 5])[::-1]
print("Reversed Array:", arr_rev)

# b)
def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_freq_value = values[np.argmax(counts)]
    indices = np.where(arr == most_freq_value)[0]
    return most_freq_value, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_x, indices_x = most_frequent(x)
most_y, indices_y = most_frequent(y)
print(f"Most frequent in x: {most_x}, Indices: {indices_x}")
print(f"Most frequent in y: {most_y}, Indices: {indices_y}")

Reversed Array: [5 4 6 3 2 1]
Most frequent in x: 1, Indices: [0 5 7 8 9]
Most frequent in y: 1, Indices: [0 1 2]


In [4]:
import numpy as np
# Q3
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

el_1_2 = arr[0, 1]

el_3_1 = arr[2, 0]

print("Element at (1,2):", el_1_2)
print("Element at (3,1):", el_3_1)

Element at (1,2): 20
Element at (3,1): 70


In [5]:
import numpy as np

# Q4
krish_arora = np.linspace(10, 100, 25)

print("Dimensions:", krish_arora.ndim)
print("Shape:", krish_arora.shape)
print("Total Elements:", krish_arora.size)
print("Data Type:", krish_arora.dtype)
print("Total Bytes Consumed:", krish_arora.nbytes)

transposed_array = krish_arora.reshape(25, 1)
print("Transposed Array using reshape:\n", transposed_array)

# Can we do the same with T attribute?
print("Using T attribute:\n", krish_arora.T)  # Not applicable for 1D array

Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes Consumed: 200
Transposed Array using reshape:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [6]:
import numpy as np

# Q5
ucs420_krish = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])

# Compute statistics
mean_val = np.mean(ucs420_krish)
median_val = np.median(ucs420_krish)
max_val = np.max(ucs420_krish)
min_val = np.min(ucs420_krish)
unique_vals = np.unique(ucs420_krish)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_vals)

# Reshape to 4 rows and 3 columns
reshaped_ucs420_krish = ucs420_krish.reshape(4, 3)
print("Reshaped Array:\n", reshaped_ucs420_krish)

# Resize to 2 rows and 3 columns
resized_ucs420_krish = np.resize(ucs420_krish, (2, 3))
print("Resized Array:\n", resized_ucs420_krish)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
 [[10 20 30]
 [40 50 60]]
